FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

# URL for the WIMS .tgz file from: https://sourcesup.renater.fr/frs/?group_id=379
ARG WIMS_URL=https://sourcesup.renater.fr/frs/download.php/file/6724/wims-4.30.tgz
ARG WIMS_VERSION=4.30

# Install packages.
RUN apt-get update && \
    apt-get -y --no-install-recommends install \
      # Install Apache
      apache2 \
      # Install required software
      make \
      g++ \
      texlive-base \
      texlive-latex-base \
      gnuplot \
      pari-gp \
      units-filter \
      flex \
      bison \
      perl \
      liburi-perl \
      imagemagick \
      libgd-dev \
      libfl-dev \
      wget \
      curl \
      # Install recommended software
      yacas \
      gap \
      maxima \
      # maxima-share is  needed since we are not installing recommended packages by default
      maxima-share  \
      octave \
      octave-statistics \
      graphviz \
      ldap-utils \
      # scilab never worked for me
      scilab-cli \
      libwebservice-validator-html-w3c-perl \
      qrencode \
      fortune \
      unzip \    
      zip \
      libgmp-dev \
      openbabel \
      # Other recommended software
      povray \
      macaulay2 \
      # Install other software
      bc \
      chemeq \
      # Install support for sending email (ssmtp alone is not enough)
      ssmtp \
      bsd-mailx \
      # Install patch
      patch \
      # Install all locales to prevent error codes on generated wims phtml files, like:
      # public_html/modules/adm/manage/lang/update.phtml.es
      locales locales-all

# Compile WIMS.
RUN adduser --disabled-password --gecos '' wims
USER wims
WORKDIR /home/wims
RUN wget -q ${WIMS_URL} && \
    tar xzf wims-${WIMS_VERSION}.tgz && \
    rm wims-${WIMS_VERSION}.tgz

# Copy all current patches. Also the script to apply them properly.
COPY patches/* /home/wims

# Apply patches to WIMS code and compile.
RUN ./apply_patches.sh && \
    rm *.patch apply_patches.sh && \
    yes "" | ./compile --mathjax --jmol --modules --geogebra --shtooka

# Configure additional software.
USER root
RUN \
# Enable CGI
    a2enmod cgid && \
# Install support for working behind a reverse proxy
    a2enmod remoteip && \
# This is required to make the default WIMS path for GAP works
    ln -s gap /usr/bin/gap.sh && \
# Configure POVray and Octave according to WIMS instructions
    echo "read+write* = /home/wims/tmp/sessions" >> /etc/povray/3.7/povray.conf && \
# Configure Octave according to WIMS instructions
    # The combination of these two options is weird. A 128k stack seems too small
    # when using the statistics package, and an error is generated by Octave. However,
    # increasing the stack size or removing entirely the option means that WIMS do not
    # recognize Octave anymore when the statistics package is loaded, while works
    # flawlessly otherwise.
    echo "pkg load statistics" >>  /etc/octaverc && \
    echo "-Xss128k" >> /usr/share/octave/6.4.0/m/java/java.opts

# Configure WIMS and final cleanup.
COPY --chmod=0755 assets/ /wims
RUN apt-get -y install --no-install-recommends lsb-release net-tools && \
    /wims/bin/post-install.sh  && \
    rm -rf /var/lib/apt/lists/*

# Metadata.
LABEL org.opencontainers.image.authors="Gianluca Amato <gianluca.amato.74@gmail.com>, Jordi Pujol-Ahulló <jordi.pujol@urv.cat>"
VOLUME /home/wims/log
VOLUME /home/wims/public_html/modules/devel
ENTRYPOINT [ "/wims/bin/entrypoint.sh" ]
EXPOSE 80/tcp
