# .env file is necessary to load the indicated variables.
services:
  wims:
    image: ${WIMS_IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WIMS_URL: ${WIMS_URL}
        WIMS_VERSION: ${WIMS_VERSION}
    security_opt:
      - seccomp:unconfined
    environment:
      MANAGER_SITE: ${MANAGER_SITE}
      TZ: ${TZ}
      WIMS_PASS: ${WIMS_PASS}
      ## Other variables may be defined here: check the README.md.
    hostname: ${container_name}
    container_name: ${container_name}
    restart: always
    ports:
      - 10000:80
